server:
  appName: web-server
  image:
    repository: tuantoquq/finance-backend
    tag: 0.0.3
    pullPolicy: IfNotPresent
  service:
    name: web-server
    tier: server
    type: ClusterIP
    protocol: TCP
    externalPort: 8181
    internalPort: 8181
  database:
    user: root
    pass: root
    dbName: master_controller
    host: mysql-primary.default.svc.cluster.local
    port: 3306
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
  dagsFolder: "/dags"
  airflowUrl: "airflow-webserver.default.svc.cluster.local:8080"
  persistence:
    name: airflow-dags-pv
    claimName: airflow-dags-pvc
    size: 1Gi
    hostPath: /root/dags
client:
  appName: web-client
  image:
    repository: tuantoquq/finance-frontend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  service:
    name: web-client
    tier: client
    type: ClusterIP
    protocol: TCP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
ingress:
  server:
    path: /api
    pathType: Prefix
  client:
    path: /
    pathType: ImplementationSpecific
  name: finance-app-ingress
  host: localhost
