server:
  appName: web-server
  image:
    repository: tuantoquq/fn-webserver
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: web-server
    tier: server
    type: ClusterIP
    protocol: TCP
    externalPort: 8181
    internalPort: 8181
  database:
    user: root
    pass: root
    dbName: manager
    host: mysql-primary.ns-mysql.svc.cluster.local
    port: 3306
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
  dagsFolder:
  airflowUrl:
client:
  appName: web-client
  image:
    repository: tuantoquq/fn-webadmin
    tag: 1.0.1
    pullPolicy: IfNotPresent
  service:
    name: web-client
    tier: client
    type: ClusterIP
    protocol: TCP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
ingress:
  server:
    path: /api
    pathType: Prefix
  client:
    path: /
    pathType: ImplementationSpecific
  name: finance-app-ingress
  host: localhost
