server:
  appName: web-server
  image:
    repository: tuantoquq/fn-webserver
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: web-server
    tier: server
    type: LoadBalancer
    protocol: TCP
    externalPort: 8181
    internalPort: 8181
  database:
    user: root
    pass: root
    dbName: manager
    host: mysql-primary.default.svc.cluster.local
    port: 3306
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
client:
  appName: web-client
  image:
    repository: tuantoquq/fn-webadmin
    tag: 1.0.4
    pullPolicy: IfNotPresent
  service:
    name: web-client
    tier: client
    type: LoadBalancer
    protocol: TCP
    externalPort: 3000
    internalPort: 3000
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1