apiVersion: apps/v1
kind: Deployment
metadata:
  name: fn-webadmin
spec:
  selector:
    matchLabels:
      app: fn-webadmin
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fn-webadmin
    spec:
      containers:
        - image: {{ .Values.image }}
          name: fn-webadmin
          ports:
            - containerPort: {{ .Values.service.port }}
              name: fn-webadmin
