apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.server.path }}
            pathType: {{ .Values.ingress.server.pathType }}
            backend:
              service:
                name: {{ .Values.server.appName }}-service
                port:
                  number: {{ .Values.server.service.externalPort }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.client.path }}
            pathType: {{ .Values.ingress.client.pathType }}
            backend:
              service:
                name: {{ .Values.client.appName }}-service
                port:
                  number: {{ .Values.client.service.externalPort }}