#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: {{ .Values.server.persistence.name }}
#spec:
#  capacity:
#    storage: {{ .Values.server.persistence.size }}
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    path: "/"
#    server: 10.72.2.31