apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.appName }}-configmap
data:
  DB_USER: {{ .Values.database.config.user }}
  DB_PASS: {{ .Values.database.config.password }}
  DB_NAME: {{ .Values.database.config.dbName }}