server:
  appName: web-server
  image:
    repository: tuantoquq/finance-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: web-server
    tier: server
    type: LoadBalancer
    protocol: TCP
    externalPort: 8181
    internalPort: 8181
  database:
    user: root
    pass: root
    dbName: master_controller
    host: mysql-primary.ns-mysql.svc.cluster.local
    port: 3306
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
  dagsFolder: "/dags"
  airflowUrl: "http://airflow-webserver.ns-airflow.svc.cluster.local:8080"
  airflowUser: admin
  airflowPass: admin
  druidOverlord: "http://druid-overlord.ns-druid.svc.cluster.local:8081"
  druidBroker: "http://druid-broker.ns-druid.svc.cluster.local:8082"
  druidUrl: "druid/v2"
  persistence:
    name: airflow-dags-pv
    claimName: airflow-dags-pvc
    size: 1Gi
    hostPath: /mnt
client:
  appName: web-client
  image:
    repository: tuantoquq/finance-frontend
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    name: web-client
    tier: client
    type: ClusterIP
    protocol: TCP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 128Mi
  replicaCount: 1
